name: Build and Push (oprf-service-setup)

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - 'oprf-service-setup-v*'

jobs:
  workflow:
    uses: ./.github/workflows/build-and-push.yml
    with:
      image-name: oprf-service-setup
      dockerfile: build/Dockerfile.oprf-service-setup

