name: Build and Push (oprf-key-gen)

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - 'oprf-key-gen-v*'

jobs:
  workflow:
    uses: ./.github/workflows/build-and-push.yml
    with:
      image-name: oprf-key-gen
      dockerfile: build/Dockerfile.oprf-key-gen

