name: Noir Tests

on:
  push:
    branches:
      - main
    tags-ignore:
      - v*
  pull_request:

jobs:
  test:
    name: Noir Unit/KAT Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./noir
    steps:
      - uses: actions/checkout@v6
      - run: curl -L https://raw.githubusercontent.com/noir-lang/noirup/main/install | bash
      - run: ~/.nargo/bin/noirup
      - run: cd babyjubjub && ~/.nargo/bin/nargo test
      - run: cd eddsa_poseidon2 && ~/.nargo/bin/nargo test
      - run: cd oprf && ~/.nargo/bin/nargo test
